AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for the instances.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access.

  ImageId:
    Type: AWS::EC2::Image::Id
    Description: The AMI ID for the EC2 instances.

Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.eu-north-1.amazonaws.com/vpc-stack.yml"

  SubnetStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.eu-north-1.amazonaws.com/subnet-stack.yml"

  EC2Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.eu-north-1.amazonaws.com/ec2-stack.yml"

  AutoScalingStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.eu-north-1.amazonaws.com/autoscaling-stack.yml"

  ELBStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.eu-north-1.amazonaws.com/load-balancer-stack.yml"
