AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.amazonaws.com/vpc-stack.yaml"

  SubnetStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.amazonaws.com/subnet-stack.yaml"

  EC2Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.amazonaws.com/ec2-stack.yaml"

  ELBStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://pkatu-bucket-01.s3.amazonaws.com/elb-stack.yaml"
