AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !ImportValue VPCStack:VPCID
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !ImportValue VPCStack:VPCID
      CidrBlock: "10.0.2.0/24"
      AvailabilityZone: !Select [1, !GetAZs ""]

  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !ImportValue VPCStack:VPCID
      CidrBlock: "10.0.3.0/24"
      AvailabilityZone: !Select [1, !GetAZs ""]
